version: '3.7'
services:
  gateway:
    image: chrisquinn/csc648-gate
    ports:
      - "4000:4000"
    deploy:
      replicas: 1
    networks:
      - webnet
    environment:
      - FRONT_END_HOST=http://frontend:3000
      - TODO_HOST=http://todo:4001
  frontend:
    image : chrisquinn/csc648-frontend
    ports:
      - "3000:3000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - webnet
  todo:
    image : chrisquinn/csc648-todo
    ports:
      - "4001:4001"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - webnet    
networks:
  webnet: